- name: Expense backend setup
  hosts: all
  become: yes
  tasks:
    - name: Disable NodeJs default version
      ansible.builtin.shell: dnf module disable nodejs -y
    - name: Enable NodeJs 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: Installing NodeJs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    - name: Copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add application user
      ansible.builtin.user:
        name: expense
    - name: Delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: Create old app content
      ansible.builtin.file:
        path: /app
        state: directory
    - name: Download and Extract the backend Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: Download NodeJs dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app        #It will go to /app directory and do npm install
    - name: Install Mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Load schema
      ansible.builtin.shell: mysql -h mysql-dev.devopspv24.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes