- name: Disable NodeJs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Installing NodeJs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Copy backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add application user
  ansible.builtin.user:
    name: expense

- name: Import common role - App Pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /app
    component: backend
    app_user: expense

- name: Download NodeJs dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app        #It will go to /app directory and do npm install

- name: Install New Relic NodeJS Library
  ansible.builtin.shell: npm install newrelic --save
  args:
    chdir: /app

- name: Copy backend StartUP Script
  ansible.builtin.template:
    src: run.sh
    dest: /app/run.sh

- name: Install Mysql client
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load schema
  ansible.builtin.shell: mysql -h {{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_HOST', region='us-east-1' ) }} -u{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_USER', region='us-east-1' ) }} -p{{ lookup('amazon.aws.aws_ssm', 'backend.{{env}}.DB_PASS', region='us-east-1' ) }} < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Import ELK Role - Filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

##