- name: Copy Elastic Yum Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install Filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed